// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/transport_sockets/tls/cert_validator/extension/v3alpha/tls_extension_validator_config.proto

package tlsv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExtensionCertValidatorConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExtensionCertValidatorConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExtensionCertValidatorConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExtensionCertValidatorConfigMultiError, or nil if none found.
func (m *ExtensionCertValidatorConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ExtensionCertValidatorConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetExtensions()) < 1 {
		err := ExtensionCertValidatorConfigValidationError{
			field:  "Extensions",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetExtensions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExtensionCertValidatorConfigValidationError{
						field:  fmt.Sprintf("Extensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExtensionCertValidatorConfigValidationError{
						field:  fmt.Sprintf("Extensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExtensionCertValidatorConfigValidationError{
					field:  fmt.Sprintf("Extensions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ExtensionCertValidatorConfigMultiError(errors)
	}

	return nil
}

// ExtensionCertValidatorConfigMultiError is an error wrapping multiple
// validation errors returned by ExtensionCertValidatorConfig.ValidateAll() if
// the designated constraints aren't met.
type ExtensionCertValidatorConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtensionCertValidatorConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtensionCertValidatorConfigMultiError) AllErrors() []error { return m }

// ExtensionCertValidatorConfigValidationError is the validation error returned
// by ExtensionCertValidatorConfig.Validate if the designated constraints
// aren't met.
type ExtensionCertValidatorConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtensionCertValidatorConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtensionCertValidatorConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtensionCertValidatorConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtensionCertValidatorConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtensionCertValidatorConfigValidationError) ErrorName() string {
	return "ExtensionCertValidatorConfigValidationError"
}

// Error satisfies the builtin error interface
func (e ExtensionCertValidatorConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtensionCertValidatorConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtensionCertValidatorConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtensionCertValidatorConfigValidationError{}

// Validate checks the field values on ExtensionCertValidatorConfig_Extension
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ExtensionCertValidatorConfig_Extension) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ExtensionCertValidatorConfig_Extension with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ExtensionCertValidatorConfig_ExtensionMultiError, or nil if none found.
func (m *ExtensionCertValidatorConfig_Extension) ValidateAll() error {
	return m.validate(true)
}

func (m *ExtensionCertValidatorConfig_Extension) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKey()) < 1 {
		err := ExtensionCertValidatorConfig_ExtensionValidationError{
			field:  "Key",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetValue()) < 1 {
		err := ExtensionCertValidatorConfig_ExtensionValidationError{
			field:  "Value",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ExtensionCertValidatorConfig_ExtensionMultiError(errors)
	}

	return nil
}

// ExtensionCertValidatorConfig_ExtensionMultiError is an error wrapping
// multiple validation errors returned by
// ExtensionCertValidatorConfig_Extension.ValidateAll() if the designated
// constraints aren't met.
type ExtensionCertValidatorConfig_ExtensionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtensionCertValidatorConfig_ExtensionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtensionCertValidatorConfig_ExtensionMultiError) AllErrors() []error { return m }

// ExtensionCertValidatorConfig_ExtensionValidationError is the validation
// error returned by ExtensionCertValidatorConfig_Extension.Validate if the
// designated constraints aren't met.
type ExtensionCertValidatorConfig_ExtensionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtensionCertValidatorConfig_ExtensionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtensionCertValidatorConfig_ExtensionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtensionCertValidatorConfig_ExtensionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtensionCertValidatorConfig_ExtensionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtensionCertValidatorConfig_ExtensionValidationError) ErrorName() string {
	return "ExtensionCertValidatorConfig_ExtensionValidationError"
}

// Error satisfies the builtin error interface
func (e ExtensionCertValidatorConfig_ExtensionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtensionCertValidatorConfig_Extension.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtensionCertValidatorConfig_ExtensionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtensionCertValidatorConfig_ExtensionValidationError{}
